### ISSUE TITLE
Erreurs sur la commande !trusted

### ISSUE THREAD

**Issue by A-xis** [thilp/vlb-rb#11]
Sur #Vikidia :
08:58:03 @Vivi-XPTDR !trust Vivi-XPTDR
08:58:03 <+VikiLinkBot> Vivi-XPTDR peut désormais utiliser les commandes à accès restreint.

En privée avec le bot :
08:57:47 -!- Irssi: Starting query in Freenode with VikiLinkBot
08:57:47 <Vivi-XPTDR> !trusted
08:57:47 <VikiLinkBot> Désolé, vous n'avez pas le niveau de privilèges requis (whitelisted?)
08:58:09 <Vivi-XPTDR> !trusted
08:58:09 <VikiLinkBot> Oups ! Exception non rattrapée : undefined method `name' for nil:NilClass

Une erreur semble s'être glissé quelque part ;)

**Comment by thilp** [comment]
Oui, toute l'architecture actuelle de contrôle d'accès est complètement moisie, et je ne la maintiens pas (elle n'est pas gênante pour les autres tâches). Sur la branche de développement, j'ai un système bien meilleur (avec des groupes, de la délégation de confiance, etc.) mais il est pas encore prêt.

Merci donc pour ce retour que je vais ignorer pour le moment ! :dancer:
