### ISSUE TITLE
Improving !status command

### ISSUE THREAD

**Issue by A-xis** [thilp/vlb-rb#15]
Sometimes, it should be useful to add an acknowledgement to an error displayed when using !status

for examples : 10:21:56 <+VikiLinkBot> [VSC] download.vikidia.org: SSL_connect returned=1 errno=0 state=unknown state: certificate verify failed
Is a recurring, and known error.

This can be added to !status, but, shall be used only by operator.

**Comment by thilp** [comment]
This feature has been added in v2.4.5 on rc. Thank you!
